# -----------------------
# Development Dockerfile
# -----------------------

FROM python:3.12-slim

# Install system packages
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy requirements
COPY requirements.txt .

# Install dependencies (without caching)
RUN pip install --no-cache-dir -r requirements.txt

# Copy entire project
COPY . .

# Expose dev port
EXPOSE 5000

# Run flask app in development mode
CMD ["python", "app.py"]
